// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvraqxexfduoylpofoec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2cmFxeGV4ZmR1b3lscG9mb2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDEwMjMsImV4cCI6MjA2NTg3NzAyM30.Vq_y8oKi7cE2LoC-R0_PIThQx7FtHB0leFX3Vdshqpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);